CREATE TABLE stats (
    average_sum DOUBLE PRECISION,
    max_sum INTEGER,
    min_sum INTEGER,
    last_sum INTEGER,
    sum_std DOUBLE PRECISION,
    max_odd_count INTEGER,
    max_even_count INTEGER,
    max_prime_count INTEGER,
    max_fibonacci_count INTEGER,
    last_odd_count INTEGER,
    last_even_count INTEGER,
    last_prime_count INTEGER,
    last_fibonacci_count INTEGER,
    fibonacci_count_std DOUBLE PRECISION,
    prime_count_std DOUBLE PRECISION,
    even_count_std DOUBLE PRECISION,
    odd_count_std DOUBLE PRECISION,
    average_odd_count DOUBLE PRECISION,
    average_even_count DOUBLE PRECISION,
    average_prime_count DOUBLE PRECISION,
    average_fibonacci_count DOUBLE PRECISION,
    min_odd_count INTEGER,
    min_even_count INTEGER,
    min_prime_count INTEGER,
    min_fibonacci_count INTEGER,
    last_bola1 INTEGER,
    last_bola2 INTEGER,
    last_bola3 INTEGER,
    last_bola13 INTEGER,
    last_bola14 INTEGER,
    last_bola15 INTEGER,
    average_bola1 DOUBLE PRECISION,
    average_bola2 DOUBLE PRECISION,
    average_bola3 DOUBLE PRECISION,
    average_bola13 DOUBLE PRECISION,
    average_bola14 DOUBLE PRECISION,
    average_bola15 DOUBLE PRECISION,
    max_bola1 INTEGER,
    max_bola2 INTEGER,
    max_bola3 INTEGER,
    max_bola13 INTEGER,
    max_bola14 INTEGER,
    max_bola15 INTEGER,
    min_bola13 INTEGER,
    min_bola14 INTEGER,
    min_bola15 INTEGER,
    bola13_std DOUBLE PRECISION,
    bola14_std DOUBLE PRECISION,
    bola15_std DOUBLE PRECISION
);
