version: '3.1'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: artur
      POSTGRES_PASSWORD: Aqwe123!
      POSTGRES_DB: lotofacil
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
